version: "3.1"
services:
  mealie-frontend:
    container_name: mealie-frontend
    image: mealie-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9091:3000
    environment:
      - GLOBAL_MIDDLEWARE=null
      - BASE_URL=""
      - ALLOW_SIGNUP=true
  mealie:
    container_name: mealie-api
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9092:80
    environment:
      # DB_ENGINE: postgres # Optional: 'sqlite', 'postgres'
      # POSTGRES_USER: mealie
      # POSTGRES_PASSWORD: mealie
      # POSTGRES_SERVER: postgres
      # POSTGRES_PORT: 5432
      # POSTGRES_DB: mealie
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
      WEB_CONCURRENCY: 2
